    export const EX = [
      // Ngực
      { id: 'bench-press', name: 'Bench Press', g: 'Ngực' },
      { id: 'incline-bench', name: 'Incline Bench Press', g: 'Ngực' },
      { id: 'decline-bench', name: 'Decline Bench Press', g: 'Ngực' },
      { id: 'dumbbell-press', name: 'Dumbbell Press', g: 'Ngực' },
      { id: 'incline-db-press', name: 'Incline Dumbbell Press', g: 'Ngực' },
      { id: 'cable-fly', name: 'Cable Fly', g: 'Ngực' },
      { id: 'low-cable-fly', name: 'Low Cable Fly', g: 'Ngực' },
      { id: 'dumbbell-fly', name: 'Dumbbell Fly', g: 'Ngực' },
      { id: 'pec-deck', name: 'Pec Deck (Machine Fly)', g: 'Ngực' },
      { id: 'chest-dip', name: 'Chest Dip', g: 'Ngực' },
      { id: 'machine-chest', name: 'Machine Chest Press', g: 'Ngực' },
      { id: 'push-up', name: 'Push-up', g: 'Ngực' },
      // Chân
      { id: 'squat', name: 'Squat', g: 'Chân' },
      { id: 'leg-press', name: 'Leg Press', g: 'Chân' },
      { id: 'rdl', name: 'Romanian Deadlift', g: 'Chân' },
      { id: 'leg-curl', name: 'Leg Curl (Lying)', g: 'Chân' },
      { id: 'seated-leg-curl', name: 'Leg Curl (Seated)', g: 'Chân' },
      { id: 'leg-ext', name: 'Leg Extension', g: 'Chân' },
      { id: 'calf-raise', name: 'Calf Raise (Standing)', g: 'Chân' },
      { id: 'seated-calf', name: 'Calf Raise (Seated)', g: 'Chân' },
      { id: 'bulgarian-split', name: 'Bulgarian Split Squat', g: 'Chân' },
      { id: 'hack-squat', name: 'Hack Squat', g: 'Chân' },
      { id: 'goblet-squat', name: 'Goblet Squat', g: 'Chân' },
      { id: 'sumo-squat', name: 'Sumo Squat', g: 'Chân' },
      { id: 'walking-lunge', name: 'Walking Lunge', g: 'Chân' },
      { id: 'leg-press-calf', name: 'Leg Press Calf Raise', g: 'Chân' },
      { id: 'sissy-squat', name: 'Sissy Squat', g: 'Chân' },
      { id: 'back-squat', name: 'Back Squat', g: 'Chân' },
      { id: 'front-squat', name: 'Front Squat', g: 'Chân' },
      { id: 'single-leg-press', name: 'Single-Leg Leg Press', g: 'Chân' },
      { id: 'single-leg-ext', name: 'Single-Leg Leg Extension', g: 'Chân' },
      { id: 'swiss-ball-leg-curl', name: 'Swiss Ball Single-Leg Leg Curl', g: 'Chân' },
      // Lưng
      { id: 'deadlift', name: 'Deadlift', g: 'Lưng' },
      { id: 'barbell-row', name: 'Barbell Row', g: 'Lưng' },
      { id: 'lat-pull', name: 'Lat Pulldown', g: 'Lưng' },
      { id: 'pull-up', name: 'Pull-up', g: 'Lưng' },
      { id: 'chin-up', name: 'Chin-up', g: 'Lưng' },
      { id: 'seated-row', name: 'Seated Cable Row', g: 'Lưng' },
      { id: 't-bar-row', name: 'T-Bar Row', g: 'Lưng' },
      { id: 'single-arm-row', name: 'Single Arm Dumbbell Row', g: 'Lưng' },
      { id: 'straight-arm-pull', name: 'Straight Arm Pulldown', g: 'Lưng' },
      { id: 'chest-supported-row', name: 'Chest Supported Row', g: 'Lưng' },
      { id: 'rack-pull', name: 'Rack Pull', g: 'Lưng' },
      { id: 'hyperextension', name: 'Hyperextension', g: 'Lưng' },
      { id: 'meadows-row', name: 'Meadows Row', g: 'Lưng' },
      { id: 'lat-pull-in', name: '1 Arm Lat Pull-in', g: 'Lưng' },
      { id: 'pendlay-row', name: 'Pendlay Row', g: 'Lưng' },
      { id: 'machine-high-row', name: 'Machine High Row', g: 'Lưng' },
      { id: 'neutral-grip-pulldown', name: 'Neutral-Grip Pulldown', g: 'Lưng' },
      { id: 'elbows-out-row', name: 'Cable Seated Elbows-Out Row', g: 'Lưng' },
      { id: 'cable-pullover', name: 'Straight-Arm Cable Pullover', g: 'Lưng' },
      { id: 'barbell-shrug', name: 'Barbell Shrug', g: 'Lưng' },
      // Vai
      { id: 'ohp', name: 'Overhead Press (Barbell)', g: 'Vai' },
      { id: 'db-shoulder-press', name: 'Dumbbell Shoulder Press', g: 'Vai' },
      { id: 'arnold-press', name: 'Arnold Press', g: 'Vai' },
      { id: 'lateral-raise', name: 'Lateral Raise', g: 'Vai' },
      { id: 'cable-lateral-raise', name: 'Cable Lateral Raise', g: 'Vai' },
      { id: 'face-pull', name: 'Face Pull', g: 'Vai' },
      { id: 'front-raise', name: 'Front Raise', g: 'Vai' },
      { id: 'reverse-fly', name: 'Reverse Fly (Dumbbell)', g: 'Vai' },
      { id: 'upright-row', name: 'Upright Row', g: 'Vai' },
      { id: 'machine-shoulder', name: 'Machine Shoulder Press', g: 'Vai' },
      { id: 'rear-delt-fly', name: 'Rear Delt Fly (Machine)', g: 'Vai' },
      { id: 'cable-face-pull', name: 'Cable Face Pull', g: 'Vai' },
      { id: 'military-press', name: 'Military Press', g: 'Vai' },
      { id: 'cable-reverse-fly', name: 'Cable Reverse Fly', g: 'Vai' },
      // Tay
      { id: 'bicep-curl', name: 'Barbell Curl', g: 'Tay' },
      { id: 'db-curl', name: 'Dumbbell Curl', g: 'Tay' },
      { id: 'hammer-curl', name: 'Hammer Curl', g: 'Tay' },
      { id: 'preacher-curl', name: 'Preacher Curl', g: 'Tay' },
      { id: 'concentration-curl', name: 'Concentration Curl', g: 'Tay' },
      { id: 'incline-db-curl', name: 'Incline Dumbbell Curl', g: 'Tay' },
      { id: 'cable-curl', name: 'Cable Curl', g: 'Tay' },
      { id: 'ez-bar-curl', name: 'EZ Bar Curl', g: 'Tay' },
      { id: 'reverse-curl', name: 'Reverse Curl', g: 'Tay' },
      { id: 'tricep-push', name: 'Tricep Pushdown (Cable)', g: 'Tay' },
      { id: 'skull-crusher', name: 'Skull Crusher', g: 'Tay' },
      { id: 'overhead-tricep', name: 'Overhead Tricep Extension', g: 'Tay' },
      { id: 'close-grip-bench', name: 'Close Grip Bench Press', g: 'Tay' },
      { id: 'tricep-kickback', name: 'Tricep Kickback', g: 'Tay' },
      { id: 'cable-overhead-tricep', name: 'Cable Overhead Tricep Ext.', g: 'Tay' },
      { id: 'reverse-grip-ez-curl', name: 'Reverse Grip EZ Bar Curl', g: 'Tay' },
      { id: 'supinated-ez-curl', name: 'Supinated EZ Bar Curl', g: 'Tay' },
      { id: 'single-arm-cable-curl', name: 'Single-Arm Cable Curl', g: 'Tay' },
      { id: 'cable-tricep-kickback', name: 'Cable Triceps Kickback', g: 'Tay' },
      // Mông
      { id: 'hip-thrust', name: 'Hip Thrust', g: 'Mông' },
      { id: 'glute-bridge', name: 'Glute Bridge', g: 'Mông' },
      { id: 'cable-kickback', name: 'Cable Kickback', g: 'Mông' },
      { id: 'donkey-kick', name: 'Donkey Kick', g: 'Mông' },
      { id: 'sumo-deadlift', name: 'Sumo Deadlift', g: 'Mông' },
      { id: 'step-up', name: 'Step-up', g: 'Mông' },
      { id: 'abductor', name: 'Hip Abductor (Machine)', g: 'Mông' },
      { id: 'adductor', name: 'Hip Adductor (Machine)', g: 'Mông' },
      { id: 'cable-pull-through', name: 'Cable Pull Through', g: 'Mông' },
      // Bụng
      { id: 'plank', name: 'Plank (giây)', g: 'Bụng' },
      { id: 'side-plank', name: 'Side Plank (giây)', g: 'Bụng' },
      { id: 'crunch', name: 'Crunch', g: 'Bụng' },
      { id: 'cable-crunch', name: 'Cable Crunch', g: 'Bụng' },
      { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', g: 'Bụng' },
      { id: 'ab-wheel', name: 'Ab Wheel Rollout', g: 'Bụng' },
      { id: 'russian-twist', name: 'Russian Twist', g: 'Bụng' },
      { id: 'sit-up', name: 'Sit-up', g: 'Bụng' },
      { id: 'bicycle-crunch', name: 'Bicycle Crunch', g: 'Bụng' },
      { id: 'leg-raise', name: 'Leg Raise (Lying)', g: 'Bụng' },
      { id: 'toe-touch', name: 'Toe Touch Crunch', g: 'Bụng' },
    ];
