// src/strings.js — catalog chuỗi GIAO DIỆN. Hai bảng cùng bộ khóa.
// Quy ước khóa: '<màn/nhóm>.<tên>'. Biến nội suy: '{n}', '{name}'…
// Thêm chuỗi = thêm cùng khóa vào CẢ vi và en. Thiếu ở en → tự fallback về vi.
// Migrate dần theo đợt (xem plan). Đợt 0: common + ngôn ngữ.

export const STR = {
  vi: {
    // ── Dùng chung ──────────────────────────────
    'common.save': 'Lưu',
    'common.cancel': 'Huỷ',
    'common.delete': 'Xoá',
    'common.back': 'Quay lại',
    'common.close': 'Đóng',
    'common.edit': 'Sửa',
    'common.done': 'Xong',
    'common.loading': 'Đang tải…',
    'common.required': 'Bắt buộc',

    // ── Form ghi buổi tập (dùng chung LogActivity + SaveWorkout) ─
    'log.more': 'Thêm chi tiết',
    'log.less': 'Ẩn bớt',
    'log.laps': 'Chia chặng / lap (tuỳ chọn)',
    'log.addLap': 'Thêm chặng',
    'log.needDistance': 'Nhập quãng đường để tính điểm',
    'log.needDuration': 'Nhập thời lượng để tính điểm',
    'log.titlePlaceholder': 'Tiêu đề (VD: {sport} sáng)',
    'log.guideLink': 'Hướng dẫn {sport} cho người mới',
    'points.earned': 'Buổi này được',
    'unit.pt': 'đ',
    'photo.add': 'Thêm ảnh (tuỳ chọn)',
    'photo.note': 'Ảnh sẽ hiển thị với toàn bộ đồng nghiệp.',
    'visibility.title': 'Hiển thị',
    'visibility.company': 'Đồng nghiệp',
    'visibility.private': 'Chỉ mình tôi',
    'when.title': 'Khi nào',
    'save.discard': 'Huỷ buổi tập',
    'save.discardConfirm': 'Huỷ buổi tập?',
    'common.notFound': 'Không tìm thấy "{q}"',

    // ── Chọn môn (PickActivity) ─────────────────
    'pick.title': 'BẠN VỪA TẬP GÌ?',
    'pick.subtitle': 'Ghi lại để giữ chuỗi và cộng điểm.',
    'pick.favorites': 'BẠN HAY TẬP',
    'pick.all': 'TẤT CẢ MÔN',

    // ── Onboarding ──────────────────────────────
    'ob.welcome': 'Chào mừng!',
    'ob.intro': 'Vài thông tin để bắt đầu. Bạn có thể đổi lại bất cứ lúc nào trong Cài đặt.',
    'ob.name': 'Tên hiển thị',
    'ob.namePlaceholder': 'Tên của bạn',
    'ob.dept': 'Phòng ban / Trung tâm',
    'ob.deptPlaceholder': 'Chọn hoặc gõ để tìm…',
    'ob.sports': 'Môn bạn hay tập (tuỳ chọn)',
    'ob.privacyTitle': 'Riêng tư:',
    'ob.privacyBody': 'Cân nặng và số đo của bạn luôn riêng tư, không ai thấy. Buổi tập của bạn hiển thị với đồng nghiệp trong bảng tin — bạn có thể đặt riêng tư từng buổi bất cứ lúc nào.',
    'ob.start': 'Bắt đầu',
    'ob.saving': 'Đang lưu…',

    // ── Màn mừng sau buổi tập ───────────────────
    'celeb.title': 'Xong buổi {sport}!',
    'celeb.streakUp': 'Chuỗi của bạn lên {n} ngày.',
    'celeb.streakRecord': 'Chuỗi của bạn lên {n} ngày — kỷ lục mới!',
    'celeb.streakFirst': 'Buổi đầu tiên — chuỗi bắt đầu từ hôm nay.',
    'celeb.newBadges': 'Huy hiệu mới',
    'celeb.newPR': 'PR mới',
    'celeb.toFeed': 'Về bảng tin',

    // ── Trang chủ ───────────────────────────────
    'home.streak': 'CHUỖI LIÊN TIẾP',
    'home.days': 'NGÀY',
    'home.total': 'TỔNG BUỔI TẬP',
    'home.sessions': 'BUỔI',
    'home.atRisk': 'Tập hôm nay để giữ chuỗi {n} ngày nhé!',
    'home.weekSessions': 'Buổi tuần',
    'home.minutes': 'Phút',
    'home.weeklyGoal': 'MỤC TIÊU TUẦN',
    'home.ofSessions': '/{n} buổi',
    'home.goalDone': 'Vượt mục tiêu tuần này rồi. Đặt mốc cao hơn?',
    'home.goalLeft': 'Còn {n} buổi nữa là đạt mục tiêu tuần.',
    'home.recent': 'GẦN ĐÂY',
    'home.seeAll': 'Tất cả ›',

    // ── Ngôn ngữ (Settings + SignIn) ────────────
    'lang.title': 'Ngôn ngữ',
    'lang.vi': 'Tiếng Việt',
    'lang.en': 'English',

    // ── Mức gắng sức (RPE) ──────────────────────
    'rpe.field.label': 'Buổi tập nặng cỡ nào?',
    'rpe.field.hint': 'Chọn theo cảm giác trong lúc tập, không phải sau khi xong.',
    'rpe.1.label': 'Rất nhẹ',
    'rpe.1.desc': 'Như đi dạo. Thở đều, hát được cả bài, tập cả tiếng cũng không mệt.',
    'rpe.2.label': 'Nhẹ',
    'rpe.2.desc': 'Ấm người, ra mồ hôi nhẹ. Vẫn trò chuyện thoải mái từng câu.',
    'rpe.3.label': 'Vừa',
    'rpe.3.desc': 'Thở gấp hơn, nói được câu dài nhưng hát thì hụt hơi. Đang gắng nhưng vẫn kiểm soát.',
    'rpe.4.label': 'Nặng',
    'rpe.4.desc': 'Thở dốc, mỗi lần chỉ nói được vài từ. Cơ mỏi, bắt đầu muốn nghỉ.',
    'rpe.5.label': 'Gắng sức tối đa',
    'rpe.5.desc': 'Hết sức. Gần như không nói nổi, tim đập mạnh, chỉ trụ thêm được chút.',

    // ── Ghi buổi tập / nhật ký ──────────────────
    'save.note.title': 'Nhật ký buổi tập',
    'save.note.placeholder': 'VD: Chạy xong đầu óc nhẹ hẳn — đúng thứ mình cần hôm nay.',
    'edit.titleLabel': 'Tiêu đề',

    // ── Tên môn (hiển thị) ──────────────────────
    'sport.gym.label': 'Tập gym', 'sport.gym.verb': 'đã hoàn thành buổi',
    'sport.run.label': 'Chạy bộ', 'sport.run.verb': 'đã chạy',
    'sport.walk.label': 'Đi bộ', 'sport.walk.verb': 'đã đi bộ',
    'sport.cycle.label': 'Đạp xe', 'sport.cycle.verb': 'đã đạp xe',
    'sport.swim.label': 'Bơi', 'sport.swim.verb': 'đã bơi',
    'sport.hiking.label': 'Leo núi', 'sport.hiking.verb': 'đã leo núi',
    'sport.yoga.label': 'Yoga', 'sport.yoga.verb': 'đã tập yoga',
    'sport.football.label': 'Bóng đá', 'sport.football.verb': 'đã chơi bóng đá',
    'sport.basketball.label': 'Bóng rổ', 'sport.basketball.verb': 'đã chơi bóng rổ',
    'sport.badminton.label': 'Cầu lông', 'sport.badminton.verb': 'đã chơi cầu lông',
    'sport.tennis.label': 'Tennis', 'sport.tennis.verb': 'đã chơi tennis',
    'sport.pickleball.label': 'Pickleball', 'sport.pickleball.verb': 'đã chơi pickleball',
    'sport.other.label': 'Khác', 'sport.other.verb': 'đã tập',

    // ── Nhãn ô nhập ─────────────────────────────
    'field.durationMin': 'Thời lượng (phút)',
    'field.distanceKm': 'Quãng đường (km)',
    'field.distanceM': 'Quãng đường (m)',
    'field._pace': 'Pace',
    'field._pace100': 'Pace /100m',
    'field._speed': 'Tốc độ TB',
    'field.elevM': 'Độ cao (m)',
    'field.elevGainM': 'Độ cao leo (m)',
    'field.hrAvg': 'Nhịp tim TB (bpm)',
    'field.stepK': 'Số bước (nghìn)',
    'field.place': 'Địa điểm',
    'field.poolLen': 'Chiều dài bể',
    'field.goal': 'Mục tiêu',
    'field.periods': 'Số hiệp',
    'field.games': 'Số ván',

    // ── Đơn vị ──────────────────────────────────
    'unit.min': 'phút',
    'unit.points': 'điểm',
    'stat.duration': 'Thời lượng',
    'stat.effort': 'Gắng sức',
    'stat.points': 'Điểm',
    'stat.distance': 'Quãng đường',
    'stat.pace': 'Pace',
    'stat.avgSpeed': 'Tốc độ TB',
    'stat.volume': 'Tổng volume',
    'stat.sets': 'Tổng set',
    'stat.time': 'Thời gian',
    'stat.exCount': 'Số bài tập',
    'stat.generic': 'Chỉ số',
    'unit.ex': 'bài',

    // ── Chương trình gym (ProgsTab / CreateProg / PickEx) ───────
    'progs.title': 'Chương trình',
    'progs.new': 'Tạo mới',
    'progs.emptyMsg': 'Chưa có chương trình',
    'progs.emptySub': 'Nhấn "+ Tạo mới" để bắt đầu',
    'progs.delConfirm': 'Xoá "{name}"?',
    'cp.needName': 'Nhập tên chương trình!',
    'cp.needDayNames': 'Nhập tên cho tất cả các ngày!',
    'cp.needEx': 'Mỗi ngày cần ít nhất 1 bài tập!',
    'cp.editTitle': 'Sửa chương trình',
    'cp.newTitle': 'Tạo chương trình',
    'cp.progNamePlaceholder': 'Tên chương trình (VD: Push Pull Legs)',
    'cp.dayNamePlaceholder': 'Tên ngày (Push, Chân, Full Body...)',
    'cp.searchEx': 'Tìm bài tập…',
    'cp.addDay': 'Thêm ngày',
    'pe.title': 'Chọn bài tập',
    'pe.all': 'Tất cả',
    'pe.emptyMsg': 'Không tìm thấy bài tập',
    'pe.emptySub': 'Thử nhóm cơ khác hoặc từ khoá khác',
    'pe.newEx': 'Tạo bài tập mới',
    'pe.newExTitle': 'Bài tập mới',
    'pe.exNamePlaceholder': 'Tên bài tập…',

    // ── Đang tập (ActiveWorkout) + Lưu buổi gym ─────────────────
    'aw.training': 'Đang tập: {name}',
    'aw.resume': 'Tiếp tục',
    'aw.restTime': 'Thời gian nghỉ',
    'aw.restDone': 'Hết giờ! Tiếp tục tập thôi 🔥',
    'aw.restIn': 'Tiếp tục sau {t}',
    'aw.lastTime': 'Lần trước: {v}',
    'aw.exNote': 'Ghi chú bài tập…',
    'aw.addEx': 'Thêm bài tập',
    'sw.title': 'Lưu buổi tập',
    'sw.namePlaceholder': 'Tên buổi tập',
    'common.guide': 'Hướng dẫn',
    'common.saving': 'Đang lưu…',
    'common.add': 'Thêm',
    'common.dismiss': 'Bỏ qua',
    'common.exit': 'Thoát',
    'photo.short': 'Thêm ảnh',

    // ── Chi tiết buổi tập (sửa/xoá) ─────────────────────────────
    'sd.delConfirm': 'Xoá bài đăng này? Số liệu (điểm, phút, buổi, chuỗi, xếp hạng) sẽ được trừ lại. Không hoàn tác được.',
    'sd.photoRemoved': 'Đã gỡ ảnh — bấm để thêm ảnh mới',
    'sd.visNote': 'Chuyển sang "Chỉ mình tôi" sẽ gỡ buổi này khỏi bảng tin & bảng xếp hạng của đồng nghiệp.',
    'sd.editNote': 'Sửa tiêu đề, ghi chú & ảnh. Điểm, chuỗi và xếp hạng giữ nguyên như lúc đăng.',
    'sd.saveConfirm': 'Lưu thay đổi cho bài này?',
    'sd.laps': 'Chi tiết chặng',

    // ── Tiến độ cá nhân (ProgressTab) ───────────────────────────
    'pt.emptyMsg': 'Chưa có dữ liệu',
    'pt.emptySub': 'Hoàn thành buổi tập để thấy tiến bộ ở đây',
    'pt.weight': 'Cân nặng (riêng tư 🔒)',
    'pt.latest': 'Gần nhất',
    'pt.noData': 'Chưa có dữ liệu',
    'pt.weeklyGoal': 'Mục tiêu tuần này',
    'pt.goalPrompt': 'Đặt mục tiêu để giữ thói quen đều đặn.',
    'pt.setGoal': 'Đặt mục tiêu',
    'pt.sessPerWeek': 'Số buổi / tuần',
    'pt.minPerWeek': 'Số phút / tuần',
    'pt.goalHint': 'Để 0 nếu không đặt mục tiêu đó. Gợi ý WHO: 150 phút/tuần.',
    'pt.sessions': 'Buổi tập',
    'pt.activeMin': 'Phút vận động',
    'pt.editGoal': 'Sửa mục tiêu',
    'pt.pr': 'Kỷ lục cá nhân',
    'pt.weekPoints': 'Điểm tuần',
    'pt.weekMin': 'Phút tuần',
    'pt.weekSess': 'Buổi tuần',
    'pt.breakdown': 'Phân bổ theo môn',
    'pt.days90': '90 ngày',
    'pt.countMin': '{c} buổi · {m} phút',
    'pt.pointsByWeek': 'Điểm theo tuần',
    'pt.bestSpeed': 'Tốc độ tốt nhất',
    'pt.bestPace': 'Pace tốt nhất',
    'pt.longest': 'Dài nhất',
    'pt.sessCount': 'Số buổi',
    'pt.distByWeek': 'Quãng đường theo tuần ({u})',
    'pt.needMore': 'Cần thêm buổi để thấy xu hướng',
    'pt.totalMin': 'Tổng phút',
    'pt.totalPts': 'Tổng điểm',
    'pt.overview': 'Tổng quan',
    'pt.byExercise': 'Theo bài tập',
    'pt.bySession': 'Theo buổi tập',
    'pt.noExData': 'Chưa có dữ liệu bài tập',
    'pt.thisWeek': 'Tuần này',
    'pt.lastWeek': 'Tuần trước',
    'pt.prHeaviest': 'PR Tạ nặng nhất',
    'pt.noSessData': 'Chưa có dữ liệu buổi tập',
    'pt.mostRecent': 'Lần gần nhất',
    'pt.previous': 'Lần trước đó',
    'pt.history': 'Lịch sử các lần tập',
    'pt.weightPrompt': 'Cân nặng hôm nay (kg):',

    // ── Cấp app: lời mời, banner quản trị, lỗi ──────────────────
    'invite.title': 'Bạn có lời mời vào nhóm',
    'invite.from': '{name} mời bạn',
    'invite.generic': 'Bạn được mời',
    'admin.banner': '🛡 Chế độ quản trị đang bật — bạn có thể xoá bài & bình luận của mọi người.',
    'chat.aria': 'Trợ lý AI',
    'err.loadProfile': 'Không tải được hồ sơ',
    'err.saveGoals': 'Lưu mục tiêu thất bại',
    'err.deleteAccount': 'Không xoá được tài khoản',
    'err.uploadPhoto': 'Upload ảnh thất bại',
    'err.editSession': 'Sửa buổi tập thất bại',
    'err.changeVis': 'Đổi hiển thị thất bại',
    'err.deletePost': 'Xoá bài thất bại',
    'err.adminDelete': 'Xoá bài (quản trị) thất bại',
    'err.joinClub': 'Vào nhóm thất bại',
    'err.syncSession': 'Đồng bộ buổi tập thất bại',

    // ── Bảng tin / bài đăng / bình luận (Đợt 2) ─────────────────
    'feed.title': 'BẢNG TIN',
    'feed.newPosts': '↑ {n} bài mới',
    'feed.emptyMsg': 'Chưa có bài nào',
    'feed.emptySub': 'Hãy là người đầu tiên chia sẻ buổi tập!',
    'feed.loadingMore': 'Đang tải thêm…',
    'post.streak': 'chuỗi {n} ngày',
    'post.manage': 'Sửa / xoá bài',
    'post.adminDelConfirm': 'Xoá bài này của {name}? (Thao tác quản trị — không hoàn tác được.)',
    'post.adminDelTitle': 'Xoá bài (quản trị)',
    'post.someone': 'người dùng',
    'cmt.title': 'Bình luận',
    'cmt.saveConfirm': 'Lưu thay đổi bình luận?',
    'cmt.delConfirm': 'Xoá bình luận này?',
    'cmt.emptyMsg': 'Chưa có bình luận',
    'cmt.emptySub': 'Hãy động viên đồng nghiệp một câu!',
    'cmt.edited': 'đã sửa',
    'cmt.placeholder': 'Viết bình luận…',

    // ── Bảng xếp hạng ───────────────────────────────────────────
    'lb.title': 'BẢNG XẾP HẠNG',
    'lb.subtitle': 'Điểm quy đổi theo cường độ — công bằng giữa mọi môn.',
    'lb.company': 'Toàn công ty',
    'lb.dept': 'Phòng ban',
    'lb.week': 'Tuần này',
    'lb.month': 'Tháng này',
    'lb.you': 'Bạn',
    'lb.youParen': ' (bạn)',
    'lb.rank': 'HẠNG {n}',
    'lb.sessMin': '{s} buổi · {m} phút',
    'lb.noDeptMsg': 'Bạn chưa có phòng ban',
    'lb.noDeptSub': 'Cập nhật phòng ban trong Cài đặt để xem bảng này',
    'lb.emptyMsg': 'Chưa có ai trong kỳ này',
    'lb.emptySub': 'Ghi buổi tập đầu tiên để dẫn đầu!',
    'lb.footer': 'Bảng làm mới mỗi tuần. Bạn có thể tắt tham gia trong Cài đặt.',

    // ── Tab Cá nhân (CalendarTab) ───────────────────────────────
    'cal.clubs': 'Câu lạc bộ',
    'cal.clubsSub': 'Gặp đồng nghiệp cùng đam mê một môn',
    'cal.goals': 'Mục tiêu chung',
    'cal.goalsSub': 'Cả công ty cùng góp để về đích chung',
    'cal.guides': 'Hướng dẫn tập luyện',
    'cal.guidesSub': 'Kiến thức nhập môn cho từng bài tập',
    'cal.rankThisWeek': 'hạng {n} tuần này',
    'cal.viewStats': 'Xem thành tích ›',
    'cal.monthMin': 'Phút tháng',
    'cal.streak': 'Chuỗi',
    'cal.daysN': '{n} ngày',
    'cal.weight': 'CÂN NẶNG',
    'cal.weightNote': 'chỉ mình bạn thấy',
    'cal.notLogged': 'Chưa ghi',
    'cal.logWeight': 'Ghi',

    // ── Hồ sơ (ProfileScreen) ───────────────────────────────────
    'prof.selfTitle': 'THÀNH TÍCH CỦA BẠN',
    'prof.title': 'HỒ SƠ',
    'prof.notFound': 'Không tìm thấy hồ sơ',
    'prof.streakDays': 'Chuỗi {n} ngày',
    'prof.longestStreak': 'Chuỗi dài',
    'prof.badges': 'HUY HIỆU',
    'prof.recent': 'BUỔI TẬP GẦN ĐÂY',
    'prof.noPublic': 'Chưa có buổi tập công khai',

    // ── Huy hiệu (badges) ───────────────────────────────────────
    'badge.first.label': 'Buổi đầu tiên', 'badge.first.desc': 'Ghi lại buổi tập đầu tiên',
    'badge.streak3.label': 'Chuỗi 3 ngày', 'badge.streak3.desc': 'Tập 3 ngày liên tiếp',
    'badge.streak7.label': 'Chuỗi 7 ngày', 'badge.streak7.desc': 'Tập 7 ngày liên tiếp',
    'badge.streak30.label': 'Chuỗi 30 ngày', 'badge.streak30.desc': 'Tập 30 ngày liên tiếp',
    'badge.streak100.label': 'Chuỗi 100 ngày', 'badge.streak100.desc': 'Tập 100 ngày liên tiếp',
    'badge.comeback.label': 'Trở lại', 'badge.comeback.desc': 'Quay lại tập sau khi nghỉ',
    'badge.firstSport.label': 'Lần đầu {sport}', 'badge.firstSport.desc': 'Thử {sport} lần đầu',

    // ═══ ĐỢT 3 ═══
    'common.create': 'Tạo',

    // ── Câu lạc bộ ──────────────────────────────
    'clubs.title': 'CÂU LẠC BỘ',
    'clubs.create': 'Tạo nhóm',
    'clubs.mine': 'NHÓM CỦA BẠN',
    'clubs.discover': 'KHÁM PHÁ NHÓM',
    'clubs.joined': 'Đã vào',
    'clubs.members': '{n} thành viên',
    'clubs.privateTag': 'riêng',
    'clubs.emptyMsg': 'Chưa có câu lạc bộ nào',
    'clubs.emptySub': 'Tạo nhóm đầu tiên để rủ đồng nghiệp cùng môn!',
    'clubs.createTitle': 'TẠO CÂU LẠC BỘ',
    'clubs.nameLabel': 'TÊN NHÓM',
    'clubs.namePlaceholder': 'VD: CLB Chạy bộ Apollo',
    'clubs.sportLabel': 'MÔN',
    'clubs.accessLabel': 'QUYỀN THAM GIA',
    'clubs.public': 'Công khai',
    'clubs.publicSub': 'Ai cũng vào được',
    'clubs.needApprove': 'Cần duyệt',
    'clubs.needApproveSub': 'Chủ nhóm duyệt',
    'clubs.descLabel': 'MÔ TẢ (TUỲ CHỌN)',
    'clubs.descPlaceholder': 'Nhóm này về điều gì?',
    'clubs.creating': 'Đang tạo…',
    'club.title': 'Câu lạc bộ',
    'club.deleteTitle': 'Xoá nhóm',
    'club.leaveConfirm': 'Rời khỏi nhóm này?',
    'club.deleteConfirm': 'Xoá câu lạc bộ này? Không thể hoàn tác.',
    'club.notExist': 'Nhóm không tồn tại',
    'club.needApproveTag': 'cần duyệt',
    'club.owner': 'Chủ nhóm',
    'club.leave': 'Rời nhóm',
    'club.join': 'Tham gia',
    'club.requested': 'Đã gửi yêu cầu',
    'club.requestJoin': 'Yêu cầu tham gia',
    'club.manage': 'Quản lý nhóm',
    'club.inviteBtn': 'Mời thành viên',
    'club.gate': 'Cổng vào nhóm',
    'club.gatePublicNote': 'Ai cũng vào được ngay.',
    'club.gateInviteNote': 'Người mới phải gửi yêu cầu, bạn duyệt. Người được mời vào thẳng.',
    'club.requests': 'Yêu cầu tham gia ({n})',
    'club.approve': 'Duyệt',
    'club.deny': 'Từ chối',
    'club.groupGoals': 'Mục tiêu nhóm',
    'club.noGoals': 'Chưa có mục tiêu nào.',
    'club.noGoalsOwner': ' Tạo một mục tiêu để cả nhóm cùng phấn đấu!',
    'club.activity': 'Hoạt động của nhóm',
    'club.noPostsMsg': 'Chưa có buổi {sport} nào',
    'club.noPostsSub': 'Thành viên đăng buổi tập sẽ hiện ở đây',
    'club.inviteTitle': 'Mời vào nhóm',
    'club.searchUser': 'Tìm theo tên hoặc email…',
    'club.noUserMatch': 'Không tìm thấy ai phù hợp',
    'club.searchPrompt': 'Nhập tên hoặc email để tìm',
    'club.invited': '✓ Đã mời',
    'club.invite': 'Mời',

    // ── Mục tiêu chung ──────────────────────────
    'goals.title': 'MỤC TIÊU CHUNG',
    'goals.intro': 'Phong trào toàn công ty do ban lãnh đạo phát động. Bạn tự động góp khi tập đúng môn — không xếp hạng, chỉ cùng nhau về đích.',
    'goals.emptyMsg': 'Chưa có mục tiêu chung nào',
    'goals.emptySub': 'Tạo mục tiêu đầu tiên để cả công ty cùng phấn đấu!',
    'goal.mSessionsU': 'buổi', 'goal.mSessionsL': 'Số buổi',
    'goal.mMinutesU': 'phút', 'goal.mMinutesL': 'Số phút',
    'goal.mKmU': 'km', 'goal.mKmL': 'Quãng đường',
    'goal.upcoming': 'Sắp diễn ra',
    'goal.ended': 'Đã kết thúc',
    'goal.ongoing': 'Đang diễn ra',
    'goal.deleteConfirm': 'Xoá mục tiêu này? Không thể hoàn tác.',
    'goal.yourContribution': 'Đóng góp của bạn:',
    'goal.participants': '{n} người tham gia',
    'goal.topContributors': 'GÓP NHIỀU NHẤT',
    'goal.joinToContribute': 'Tham gia nhóm để đóng góp vào mục tiêu này.',

    // ── Form tạo mục tiêu ───────────────────────
    'gf.clubTitle': 'MỤC TIÊU NHÓM',
    'gf.companyTitle': 'MỤC TIÊU TOÀN CÔNG TY',
    'gf.nameLabel': 'TÊN MỤC TIÊU',
    'gf.namePlaceholder': 'VD: Cả nhóm chạy 1000km tháng này',
    'gf.measure': 'ĐO BẰNG',
    'gf.metricSessions': 'Số buổi',
    'gf.metricMinutes': 'Số phút',
    'gf.metricKm': 'Quãng đường (km)',
    'gf.sportRequired': 'MÔN (BẮT BUỘC)',
    'gf.sportOptional': 'MÔN (TUỲ CHỌN — ĐỂ TRỐNG = MỌI MÔN)',
    'gf.allSports': 'Mọi môn',
    'gf.sportPrefix': 'Môn:',
    'gf.fromClub': '(theo nhóm)',
    'gf.targetLabel': 'MỤC TIÊU ({u})',
    'gf.targetPlaceholder': 'VD: 1000',
    'gf.start': 'BẮT ĐẦU',
    'gf.end': 'KẾT THÚC',
    'gf.creating': 'Đang tạo…',
    'gf.create': 'Tạo mục tiêu',

    // ── Thông báo (AnnouncementFeed) ────────────
    'ann.title': 'Thông báo',
    'ann.postPlaceholder': 'Đăng thông báo cho mọi người…',
    'ann.post': 'Đăng',
    'ann.empty': 'Chưa có thông báo nào.',
    'ann.postFail': 'Đăng thông báo thất bại. Thử lại nhé.',
    'ann.editFail': 'Sửa thông báo thất bại. Thử lại nhé.',
    'ann.delConfirm': 'Xoá thông báo này?',

    // ── Trợ lý AI (ChatBot) ─────────────────────
    'chat.title': 'Trợ lý Apollo',
    'chat.subtitle': 'Tư vấn tập luyện & dinh dưỡng',
    'chat.new': 'Mới',
    'chat.greeting': 'Chào bạn 👋',
    'chat.intro': 'Mình có thể tư vấn về tập luyện và dinh dưỡng. Hỏi mình bất cứ điều gì, hoặc thử vài gợi ý dưới đây:',
    'chat.placeholder': 'Nhập câu hỏi…',
    'chat.error': 'Có lỗi xảy ra, thử lại nhé.',
    'chat.s1': 'Người mới nên bắt đầu tập gym thế nào?',
    'chat.s2': 'Ăn gì trước và sau khi chạy bộ?',
    'chat.s3': 'Gợi ý lịch tập 3 buổi/tuần',
    'chat.s4': 'Cách giãn cơ tránh đau sau tập',

    // ── Kho hướng dẫn (GuidesScreen + GuideDetail chrome) ─
    'guides.title': 'HƯỚNG DẪN TẬP LUYỆN',
    'guides.subtitle': 'Không biết bắt đầu từ đâu? Bắt đầu ở đây.',
    'guides.emptyMsg': 'Chưa có bài hướng dẫn',
    'guides.emptySub': 'Thư viện đang được bổ sung',
    'gd.watchVideo': 'Xem video hướng dẫn',
    'gd.imgStart': 'Bắt đầu',
    'gd.imgEnd': 'Kết thúc',
    'gd.imgPlaceholder': 'ảnh minh hoạ động tác',
    'gd.steps': 'Các bước thực hiện',
    'gd.stepsCount': '{n} bước',
    'gd.mistakes': 'Lỗi thường gặp',
    'gd.tips': 'Mẹo',
    'gd.safety': 'An toàn',
    'gd.credit': 'Ảnh & hướng dẫn gốc: free-exercise-db (public domain). Nội dung mang tính tham khảo, không thay thế tư vấn chuyên môn.',

    // ── PR labels (stats) + lỗi cấp thấp ────────
    'pr.longDist': 'Xa nhất 1 buổi',
    'pr.weekDist': 'Tổng tuần cao nhất',
    'pr.longMin': 'Buổi dài nhất',
    'pr.weekMin': 'Tổng phút tuần cao nhất',
    'err.deleteSessions': 'Xoá buổi tập thất bại',
    'err.deleteProfile': 'Xoá hồ sơ thất bại',
    'err.reauth': 'Đã xoá dữ liệu. Vui lòng đăng nhập lại gần đây để xoá hẳn tài khoản đăng nhập.',
    'err.deleteCloudSession': 'Xoá buổi tập trên cloud thất bại',
    'err.loadFeed': 'Không tải được bảng tin',

    // ── Đăng nhập (SignIn) ──────────────────────
    'signin.tagline': 'Cùng đồng nghiệp xây thói quen vận động — chia sẻ thành quả, giữ chuỗi, tiếp lửa cho nhau.',
    'signin.button': 'Đăng nhập với Google',
    'signin.busy': 'Đang đăng nhập…',
    'signin.fail': 'Đăng nhập thất bại. Vui lòng thử lại.',
    'signin.onlyFor': 'Chỉ dành cho tài khoản',

    // ── Cài đặt (Settings) ──────────────────────
    'settings.title': 'CÀI ĐẶT',
    'settings.profile': 'Hồ sơ',
    'settings.name': 'TÊN HIỂN THỊ',
    'settings.namePlaceholder': 'Tên của bạn',
    'settings.dept': 'PHÒNG BAN / TRUNG TÂM',
    'settings.saveProfile': 'Lưu hồ sơ',
    'settings.privacy': 'Quyền riêng tư',
    'settings.rank': 'Tham gia bảng xếp hạng',
    'settings.rankSub': 'Điểm của bạn hiển thị trên bảng xếp hạng',
    'settings.hideWeight': 'Ẩn theo dõi cân nặng',
    'settings.hideWeightSub': 'Cân nặng luôn riêng tư; bật để ẩn hẳn tính năng này',
    'settings.moderation': 'Chế độ quản trị',
    'settings.moderationSub': 'Bật để kiểm duyệt bài & bình luận vi phạm của người khác',
    'settings.account': 'Tài khoản',
    'settings.signOut': 'Đăng xuất',
    'settings.clearHistory': 'Xoá lịch sử buổi tập',
    'settings.clearHistorySub': 'Giữ tài khoản, chỉ xoá các buổi đã ghi.',
    'settings.clearConfirm': 'Xoá toàn bộ lịch sử buổi tập? Không thể hoàn tác.',
    'settings.deleteAccount': 'Xoá tài khoản',
    'settings.deleteAccountSub': 'Xoá vĩnh viễn mọi buổi tập, điểm và hồ sơ. Không thể hoàn tác.',
    'settings.deleteConfirm': 'Xoá tài khoản? Mọi buổi tập, điểm và hồ sơ sẽ mất vĩnh viễn.',
    'settings.footer': 'Cân nặng và số đo của bạn không bao giờ hiển thị với đồng nghiệp.',
  },

  en: {
    // ── Common ──────────────────────────────────
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.loading': 'Loading…',
    'common.required': 'Required',

    // ── Log session form (LogActivity + SaveWorkout) ────────────
    'log.more': 'More details',
    'log.less': 'Show less',
    'log.laps': 'Splits / laps (optional)',
    'log.addLap': 'Add split',
    'log.needDistance': 'Enter distance to score',
    'log.needDuration': 'Enter duration to score',
    'log.titlePlaceholder': 'Title (e.g. Morning {sport})',
    'log.guideLink': '{sport} guide for beginners',
    'points.earned': 'This session',
    'unit.pt': 'pt',
    'photo.add': 'Add photo (optional)',
    'photo.note': 'Your photo is visible to all colleagues.',
    'visibility.title': 'Visibility',
    'visibility.company': 'Colleagues',
    'visibility.private': 'Only me',
    'when.title': 'When',
    'save.discard': 'Discard session',
    'save.discardConfirm': 'Discard this session?',
    'common.notFound': 'No match for "{q}"',

    // ── Pick activity ───────────────────────────
    'pick.title': 'WHAT DID YOU DO?',
    'pick.subtitle': 'Log it to keep your streak and earn points.',
    'pick.favorites': 'YOUR GO-TOS',
    'pick.all': 'ALL SPORTS',

    // ── Onboarding ──────────────────────────────
    'ob.welcome': 'Welcome!',
    'ob.intro': 'A few details to get started. You can change them anytime in Settings.',
    'ob.name': 'Display name',
    'ob.namePlaceholder': 'Your name',
    'ob.dept': 'Department / Center',
    'ob.deptPlaceholder': 'Pick or type to search…',
    'ob.sports': 'Sports you usually do (optional)',
    'ob.privacyTitle': 'Privacy:',
    'ob.privacyBody': 'Your weight and measurements are always private — no one can see them. Your sessions appear to colleagues in the feed, and you can make any session private anytime.',
    'ob.start': 'Get started',
    'ob.saving': 'Saving…',

    // ── Post-session celebration ────────────────
    'celeb.title': '{sport} done!',
    'celeb.streakUp': 'Your streak is now {n} days.',
    'celeb.streakRecord': 'Your streak is now {n} days — new record!',
    'celeb.streakFirst': 'First session — your streak starts today.',
    'celeb.newBadges': 'New badge',
    'celeb.newPR': 'New PR',
    'celeb.toFeed': 'Back to feed',

    // ── Home ────────────────────────────────────
    'home.streak': 'CURRENT STREAK',
    'home.days': 'DAYS',
    'home.total': 'TOTAL SESSIONS',
    'home.sessions': 'SESSIONS',
    'home.atRisk': 'Train today to keep your {n}-day streak!',
    'home.weekSessions': 'Sessions',
    'home.minutes': 'Minutes',
    'home.weeklyGoal': 'WEEKLY GOAL',
    'home.ofSessions': '/{n} sessions',
    'home.goalDone': "You've beaten this week's goal. Aim higher?",
    'home.goalLeft': '{n} more to hit your weekly goal.',
    'home.recent': 'RECENT',
    'home.seeAll': 'See all ›',

    // ── Language ────────────────────────────────
    'lang.title': 'Language',
    'lang.vi': 'Tiếng Việt',
    'lang.en': 'English',

    // ── Effort (RPE) ────────────────────────────
    'rpe.field.label': 'How hard was it?',
    'rpe.field.hint': 'Pick how it felt during the session, not after.',
    'rpe.1.label': 'Very light',
    'rpe.1.desc': 'Like a stroll. Easy breathing, could sing, could go for an hour.',
    'rpe.2.label': 'Light',
    'rpe.2.desc': 'Warmed up, light sweat. Still chatting in full sentences.',
    'rpe.3.label': 'Moderate',
    'rpe.3.desc': 'Breathing harder, can talk but not sing. Working, still in control.',
    'rpe.4.label': 'Hard',
    'rpe.4.desc': 'Breathing heavy, only a few words at a time. Muscles tiring.',
    'rpe.5.label': 'Max effort',
    'rpe.5.desc': 'All out. Can\'t talk, heart pounding, little left in the tank.',

    // ── Log session / journal ───────────────────
    'save.note.title': 'Session journal',
    'save.note.placeholder': 'e.g. Cleared my head after that run — just what I needed today.',
    'edit.titleLabel': 'Title',

    // ── Sport names (display) ───────────────────
    'sport.gym.label': 'Gym', 'sport.gym.verb': 'finished',
    'sport.run.label': 'Running', 'sport.run.verb': 'ran',
    'sport.walk.label': 'Walking', 'sport.walk.verb': 'walked',
    'sport.cycle.label': 'Cycling', 'sport.cycle.verb': 'cycled',
    'sport.swim.label': 'Swimming', 'sport.swim.verb': 'swam',
    'sport.hiking.label': 'Hiking', 'sport.hiking.verb': 'hiked',
    'sport.yoga.label': 'Yoga', 'sport.yoga.verb': 'did yoga —',
    'sport.football.label': 'Football', 'sport.football.verb': 'played football —',
    'sport.basketball.label': 'Basketball', 'sport.basketball.verb': 'played basketball —',
    'sport.badminton.label': 'Badminton', 'sport.badminton.verb': 'played badminton —',
    'sport.tennis.label': 'Tennis', 'sport.tennis.verb': 'played tennis —',
    'sport.pickleball.label': 'Pickleball', 'sport.pickleball.verb': 'played pickleball —',
    'sport.other.label': 'Other', 'sport.other.verb': 'worked out —',

    // ── Input field labels ──────────────────────
    'field.durationMin': 'Duration (min)',
    'field.distanceKm': 'Distance (km)',
    'field.distanceM': 'Distance (m)',
    'field._pace': 'Pace',
    'field._pace100': 'Pace /100m',
    'field._speed': 'Avg speed',
    'field.elevM': 'Elevation (m)',
    'field.elevGainM': 'Elevation gain (m)',
    'field.hrAvg': 'Avg heart rate (bpm)',
    'field.stepK': 'Steps (thousands)',
    'field.place': 'Location',
    'field.poolLen': 'Pool length',
    'field.goal': 'Focus',
    'field.periods': 'Periods',
    'field.games': 'Games',

    // ── Units ───────────────────────────────────
    'unit.min': 'min',
    'unit.points': 'pts',
    'stat.duration': 'Duration',
    'stat.effort': 'Effort',
    'stat.points': 'Points',
    'stat.distance': 'Distance',
    'stat.pace': 'Pace',
    'stat.avgSpeed': 'Avg speed',
    'stat.volume': 'Total volume',
    'stat.sets': 'Total sets',
    'stat.time': 'Time',
    'stat.exCount': 'Exercises',
    'stat.generic': 'Stat',
    'unit.ex': '',

    // ── Gym programs (ProgsTab / CreateProg / PickEx) ───────────
    'progs.title': 'Programs',
    'progs.new': 'New',
    'progs.emptyMsg': 'No programs yet',
    'progs.emptySub': 'Tap "+ New" to start',
    'progs.delConfirm': 'Delete "{name}"?',
    'cp.needName': 'Enter a program name!',
    'cp.needDayNames': 'Name all days!',
    'cp.needEx': 'Each day needs at least 1 exercise!',
    'cp.editTitle': 'Edit program',
    'cp.newTitle': 'New program',
    'cp.progNamePlaceholder': 'Program name (e.g. Push Pull Legs)',
    'cp.dayNamePlaceholder': 'Day name (Push, Legs, Full Body...)',
    'cp.searchEx': 'Search exercises…',
    'cp.addDay': 'Add day',
    'pe.title': 'Pick exercise',
    'pe.all': 'All',
    'pe.emptyMsg': 'No exercises found',
    'pe.emptySub': 'Try another muscle group or keyword',
    'pe.newEx': 'Create new exercise',
    'pe.newExTitle': 'New exercise',
    'pe.exNamePlaceholder': 'Exercise name…',

    // ── Active workout + save gym session ───────────────────────
    'aw.training': 'Training: {name}',
    'aw.resume': 'Resume',
    'aw.restTime': 'Rest time',
    'aw.restDone': "Time's up! Back to it 🔥",
    'aw.restIn': 'Resume in {t}',
    'aw.lastTime': 'Last time: {v}',
    'aw.exNote': 'Exercise note…',
    'aw.addEx': 'Add exercise',
    'sw.title': 'Save session',
    'sw.namePlaceholder': 'Session name',
    'common.guide': 'Guide',
    'common.saving': 'Saving…',
    'common.add': 'Add',
    'common.dismiss': 'Dismiss',
    'common.exit': 'Exit',
    'photo.short': 'Add photo',

    // ── Session detail (edit/delete) ────────────────────────────
    'sd.delConfirm': "Delete this post? Your stats (points, minutes, sessions, streak, ranking) will be deducted. This can't be undone.",
    'sd.photoRemoved': 'Photo removed — tap to add a new one',
    'sd.visNote': 'Switching to "Only me" removes this session from your colleagues\' feed and leaderboard.',
    'sd.editNote': 'Edit title, note & photo. Points, streak and ranking stay as posted.',
    'sd.saveConfirm': 'Save changes to this post?',
    'sd.laps': 'Split details',

    // ── Personal progress (ProgressTab) ─────────────────────────
    'pt.emptyMsg': 'No data yet',
    'pt.emptySub': 'Finish a session to see your progress here',
    'pt.weight': 'Weight (private 🔒)',
    'pt.latest': 'Latest',
    'pt.noData': 'No data yet',
    'pt.weeklyGoal': "This week's goal",
    'pt.goalPrompt': 'Set a goal to keep a steady habit.',
    'pt.setGoal': 'Set goal',
    'pt.sessPerWeek': 'Sessions / week',
    'pt.minPerWeek': 'Minutes / week',
    'pt.goalHint': 'Leave 0 to skip that goal. WHO suggests 150 min/week.',
    'pt.sessions': 'Sessions',
    'pt.activeMin': 'Active minutes',
    'pt.editGoal': 'Edit goal',
    'pt.pr': 'Personal records',
    'pt.weekPoints': 'Points this week',
    'pt.weekMin': 'Minutes this week',
    'pt.weekSess': 'Sessions this week',
    'pt.breakdown': 'By sport',
    'pt.days90': '90 days',
    'pt.countMin': '{c} sessions · {m} min',
    'pt.pointsByWeek': 'Points by week',
    'pt.bestSpeed': 'Best speed',
    'pt.bestPace': 'Best pace',
    'pt.longest': 'Longest',
    'pt.sessCount': 'Sessions',
    'pt.distByWeek': 'Distance by week ({u})',
    'pt.needMore': 'Need more sessions to see a trend',
    'pt.totalMin': 'Total minutes',
    'pt.totalPts': 'Total points',
    'pt.overview': 'Overview',
    'pt.byExercise': 'By exercise',
    'pt.bySession': 'By session',
    'pt.noExData': 'No exercise data yet',
    'pt.thisWeek': 'This week',
    'pt.lastWeek': 'Last week',
    'pt.prHeaviest': 'Heaviest lift PR',
    'pt.noSessData': 'No session data yet',
    'pt.mostRecent': 'Most recent',
    'pt.previous': 'Previous',
    'pt.history': 'Session history',
    'pt.weightPrompt': "Today's weight (kg):",

    // ── App level: invites, admin banner, errors ────────────────
    'invite.title': 'You have a club invite',
    'invite.from': '{name} invited you',
    'invite.generic': "You're invited",
    'admin.banner': "🛡 Moderation mode is on — you can delete anyone's posts & comments.",
    'chat.aria': 'AI assistant',
    'err.loadProfile': "Couldn't load profile",
    'err.saveGoals': 'Failed to save goal',
    'err.deleteAccount': "Couldn't delete account",
    'err.uploadPhoto': 'Photo upload failed',
    'err.editSession': 'Failed to edit session',
    'err.changeVis': 'Failed to change visibility',
    'err.deletePost': 'Failed to delete post',
    'err.adminDelete': 'Failed to delete post (admin)',
    'err.joinClub': 'Failed to join club',
    'err.syncSession': 'Failed to sync session',

    // ── Feed / post / comments (Đợt 2) ──────────────────────────
    'feed.title': 'FEED',
    'feed.newPosts': '↑ {n} new posts',
    'feed.emptyMsg': 'No posts yet',
    'feed.emptySub': 'Be the first to share a session!',
    'feed.loadingMore': 'Loading more…',
    'post.streak': '{n}-day streak',
    'post.manage': 'Edit / delete post',
    'post.adminDelConfirm': "Delete this post by {name}? (Moderation action — can't be undone.)",
    'post.adminDelTitle': 'Delete post (admin)',
    'post.someone': 'this user',
    'cmt.title': 'Comments',
    'cmt.saveConfirm': 'Save comment changes?',
    'cmt.delConfirm': 'Delete this comment?',
    'cmt.emptyMsg': 'No comments yet',
    'cmt.emptySub': 'Cheer on a colleague!',
    'cmt.edited': 'edited',
    'cmt.placeholder': 'Write a comment…',

    // ── Leaderboard ─────────────────────────────────────────────
    'lb.title': 'LEADERBOARD',
    'lb.subtitle': 'Points scaled by intensity — fair across every sport.',
    'lb.company': 'Company',
    'lb.dept': 'Department',
    'lb.week': 'This week',
    'lb.month': 'This month',
    'lb.you': 'You',
    'lb.youParen': ' (you)',
    'lb.rank': 'RANK {n}',
    'lb.sessMin': '{s} sessions · {m} min',
    'lb.noDeptMsg': 'No department set',
    'lb.noDeptSub': 'Set your department in Settings to see this board',
    'lb.emptyMsg': 'No one yet this period',
    'lb.emptySub': 'Log the first session to lead!',
    'lb.footer': 'The board resets weekly. You can opt out in Settings.',

    // ── Me tab (CalendarTab) ────────────────────────────────────
    'cal.clubs': 'Clubs',
    'cal.clubsSub': 'Meet colleagues who love the same sport',
    'cal.goals': 'Group goals',
    'cal.goalsSub': 'The whole company chips in toward one goal',
    'cal.guides': 'Training guides',
    'cal.guidesSub': 'Beginner know-how for each exercise',
    'cal.rankThisWeek': 'rank {n} this week',
    'cal.viewStats': 'View stats ›',
    'cal.monthMin': 'Minutes this month',
    'cal.streak': 'Streak',
    'cal.daysN': '{n} days',
    'cal.weight': 'WEIGHT',
    'cal.weightNote': 'only you can see this',
    'cal.notLogged': 'Not logged',
    'cal.logWeight': 'Log',

    // ── Profile (ProfileScreen) ─────────────────────────────────
    'prof.selfTitle': 'YOUR STATS',
    'prof.title': 'PROFILE',
    'prof.notFound': 'Profile not found',
    'prof.streakDays': '{n}-day streak',
    'prof.longestStreak': 'Longest streak',
    'prof.badges': 'BADGES',
    'prof.recent': 'RECENT SESSIONS',
    'prof.noPublic': 'No public sessions yet',

    // ── Badges ──────────────────────────────────────────────────
    'badge.first.label': 'First session', 'badge.first.desc': 'Logged your first session',
    'badge.streak3.label': '3-day streak', 'badge.streak3.desc': 'Trained 3 days in a row',
    'badge.streak7.label': '7-day streak', 'badge.streak7.desc': 'Trained 7 days in a row',
    'badge.streak30.label': '30-day streak', 'badge.streak30.desc': 'Trained 30 days in a row',
    'badge.streak100.label': '100-day streak', 'badge.streak100.desc': 'Trained 100 days in a row',
    'badge.comeback.label': 'Comeback', 'badge.comeback.desc': 'Returned to training after a break',
    'badge.firstSport.label': 'First {sport}', 'badge.firstSport.desc': 'Tried {sport} for the first time',

    // ═══ ĐỢT 3 ═══
    'common.create': 'New',

    // ── Clubs ───────────────────────────────────
    'clubs.title': 'CLUBS',
    'clubs.create': 'New club',
    'clubs.mine': 'YOUR CLUBS',
    'clubs.discover': 'DISCOVER',
    'clubs.joined': 'Joined',
    'clubs.members': '{n} members',
    'clubs.privateTag': 'private',
    'clubs.emptyMsg': 'No clubs yet',
    'clubs.emptySub': 'Create the first club and invite colleagues!',
    'clubs.createTitle': 'CREATE CLUB',
    'clubs.nameLabel': 'CLUB NAME',
    'clubs.namePlaceholder': 'e.g. Apollo Running Club',
    'clubs.sportLabel': 'SPORT',
    'clubs.accessLabel': 'ACCESS',
    'clubs.public': 'Public',
    'clubs.publicSub': 'Anyone can join',
    'clubs.needApprove': 'Approval required',
    'clubs.needApproveSub': 'Owner approves',
    'clubs.descLabel': 'DESCRIPTION (OPTIONAL)',
    'clubs.descPlaceholder': 'What is this club about?',
    'clubs.creating': 'Creating…',
    'club.title': 'Club',
    'club.deleteTitle': 'Delete club',
    'club.leaveConfirm': 'Leave this club?',
    'club.deleteConfirm': "Delete this club? This can't be undone.",
    'club.notExist': 'Club not found',
    'club.needApproveTag': 'approval required',
    'club.owner': 'Owner',
    'club.leave': 'Leave',
    'club.join': 'Join',
    'club.requested': 'Request sent',
    'club.requestJoin': 'Request to join',
    'club.manage': 'Manage club',
    'club.inviteBtn': 'Invite members',
    'club.gate': 'Club access',
    'club.gatePublicNote': 'Anyone can join instantly.',
    'club.gateInviteNote': 'New people request and you approve. Invited people join directly.',
    'club.requests': 'Join requests ({n})',
    'club.approve': 'Approve',
    'club.deny': 'Decline',
    'club.groupGoals': 'Club goals',
    'club.noGoals': 'No goals yet.',
    'club.noGoalsOwner': ' Create a goal for the club to chase together!',
    'club.activity': 'Club activity',
    'club.noPostsMsg': 'No {sport} sessions yet',
    'club.noPostsSub': "Members' sessions will show up here",
    'club.inviteTitle': 'Invite to club',
    'club.searchUser': 'Search by name or email…',
    'club.noUserMatch': 'No matching people',
    'club.searchPrompt': 'Type a name or email to search',
    'club.invited': '✓ Invited',
    'club.invite': 'Invite',

    // ── Group goals ─────────────────────────────
    'goals.title': 'GROUP GOALS',
    'goals.intro': 'A company-wide push started by leadership. You contribute automatically when you train the right sport — no ranking, just reaching the finish together.',
    'goals.emptyMsg': 'No group goals yet',
    'goals.emptySub': 'Create the first goal for the whole company!',
    'goal.mSessionsU': 'sessions', 'goal.mSessionsL': 'Sessions',
    'goal.mMinutesU': 'min', 'goal.mMinutesL': 'Minutes',
    'goal.mKmU': 'km', 'goal.mKmL': 'Distance',
    'goal.upcoming': 'Upcoming',
    'goal.ended': 'Ended',
    'goal.ongoing': 'Ongoing',
    'goal.deleteConfirm': "Delete this goal? This can't be undone.",
    'goal.yourContribution': 'Your contribution:',
    'goal.participants': '{n} participants',
    'goal.topContributors': 'TOP CONTRIBUTORS',
    'goal.joinToContribute': 'Join the club to contribute to this goal.',

    // ── Goal form ───────────────────────────────
    'gf.clubTitle': 'CLUB GOAL',
    'gf.companyTitle': 'COMPANY GOAL',
    'gf.nameLabel': 'GOAL NAME',
    'gf.namePlaceholder': 'e.g. Run 1000km together this month',
    'gf.measure': 'MEASURE BY',
    'gf.metricSessions': 'Sessions',
    'gf.metricMinutes': 'Minutes',
    'gf.metricKm': 'Distance (km)',
    'gf.sportRequired': 'SPORT (REQUIRED)',
    'gf.sportOptional': 'SPORT (OPTIONAL — BLANK = ALL SPORTS)',
    'gf.allSports': 'All sports',
    'gf.sportPrefix': 'Sport:',
    'gf.fromClub': '(from club)',
    'gf.targetLabel': 'TARGET ({u})',
    'gf.targetPlaceholder': 'e.g. 1000',
    'gf.start': 'START',
    'gf.end': 'END',
    'gf.creating': 'Creating…',
    'gf.create': 'Create goal',

    // ── Announcements ───────────────────────────
    'ann.title': 'Announcements',
    'ann.postPlaceholder': 'Post an announcement…',
    'ann.post': 'Post',
    'ann.empty': 'No announcements yet.',
    'ann.postFail': 'Failed to post. Please try again.',
    'ann.editFail': 'Failed to edit. Please try again.',
    'ann.delConfirm': 'Delete this announcement?',

    // ── AI assistant (ChatBot) ──────────────────
    'chat.title': 'Apollo Assistant',
    'chat.subtitle': 'Training & nutrition advice',
    'chat.new': 'New',
    'chat.greeting': 'Hi there 👋',
    'chat.intro': 'I can help with training and nutrition. Ask me anything, or try a suggestion below:',
    'chat.placeholder': 'Type your question…',
    'chat.error': 'Something went wrong, please try again.',
    'chat.s1': 'How should a beginner start at the gym?',
    'chat.s2': 'What to eat before and after a run?',
    'chat.s3': 'Suggest a 3-day/week workout plan',
    'chat.s4': 'How to stretch to avoid soreness',

    // ── Guides (GuidesScreen + GuideDetail chrome) ─
    'guides.title': 'TRAINING GUIDES',
    'guides.subtitle': 'Not sure where to start? Start here.',
    'guides.emptyMsg': 'No guides yet',
    'guides.emptySub': 'The library is being expanded',
    'gd.watchVideo': 'Watch the video guide',
    'gd.imgStart': 'Start',
    'gd.imgEnd': 'End',
    'gd.imgPlaceholder': 'movement illustration',
    'gd.steps': 'How to do it',
    'gd.stepsCount': '{n} steps',
    'gd.mistakes': 'Common mistakes',
    'gd.tips': 'Tips',
    'gd.safety': 'Safety',
    'gd.credit': 'Images & source guide: free-exercise-db (public domain). For reference only — not a substitute for professional advice.',

    // ── PR labels (stats) + low-level errors ────
    'pr.longDist': 'Farthest in one session',
    'pr.weekDist': 'Best weekly total',
    'pr.longMin': 'Longest session',
    'pr.weekMin': 'Best weekly minutes',
    'err.deleteSessions': 'Failed to delete sessions',
    'err.deleteProfile': 'Failed to delete profile',
    'err.reauth': 'Data deleted. Please sign in again recently to fully remove your login account.',
    'err.deleteCloudSession': 'Failed to delete session in cloud',
    'err.loadFeed': "Couldn't load the feed",

    // ── Sign in ─────────────────────────────────
    'signin.tagline': 'Build a movement habit with your colleagues — share wins, keep streaks, cheer each other on.',
    'signin.button': 'Sign in with Google',
    'signin.busy': 'Signing in…',
    'signin.fail': 'Sign-in failed. Please try again.',
    'signin.onlyFor': 'Only for accounts at',

    // ── Settings ────────────────────────────────
    'settings.title': 'SETTINGS',
    'settings.profile': 'Profile',
    'settings.name': 'DISPLAY NAME',
    'settings.namePlaceholder': 'Your name',
    'settings.dept': 'DEPARTMENT / CENTER',
    'settings.saveProfile': 'Save profile',
    'settings.privacy': 'Privacy',
    'settings.rank': 'Join the leaderboard',
    'settings.rankSub': 'Your points appear on the leaderboard',
    'settings.hideWeight': 'Hide weight tracking',
    'settings.hideWeightSub': 'Weight is always private; turn on to hide the feature entirely',
    'settings.moderation': 'Moderation mode',
    'settings.moderationSub': "Turn on to moderate others' posts & comments",
    'settings.account': 'Account',
    'settings.signOut': 'Sign out',
    'settings.clearHistory': 'Clear session history',
    'settings.clearHistorySub': 'Keep your account, delete only logged sessions.',
    'settings.clearConfirm': "Delete all session history? This can't be undone.",
    'settings.deleteAccount': 'Delete account',
    'settings.deleteAccountSub': "Permanently delete all sessions, points and profile. This can't be undone.",
    'settings.deleteConfirm': 'Delete account? All sessions, points and profile will be lost forever.',
    'settings.footer': 'Your weight and measurements are never shown to colleagues.',
  },
};
