// src/strings.js — catalog chuỗi GIAO DIỆN. Hai bảng cùng bộ khóa.
// Quy ước khóa: '<màn/nhóm>.<tên>'. Biến nội suy: '{n}', '{name}'…
// Thêm chuỗi = thêm cùng khóa vào CẢ vi và en. Thiếu ở en → tự fallback về vi.
// Migrate dần theo đợt (xem plan). Đợt 0: common + ngôn ngữ.

export const STR = {
  vi: {
    // ── Dùng chung ──────────────────────────────
    'common.save': 'Lưu',
    'common.cancel': 'Huỷ',
    'common.delete': 'Xoá',
    'common.back': 'Quay lại',
    'common.close': 'Đóng',
    'common.edit': 'Sửa',
    'common.done': 'Xong',
    'common.loading': 'Đang tải…',
    'common.required': 'Bắt buộc',

    // ── Form ghi buổi tập (dùng chung LogActivity + SaveWorkout) ─
    'log.more': 'Thêm chi tiết',
    'log.less': 'Ẩn bớt',
    'log.laps': 'Chia chặng / lap (tuỳ chọn)',
    'log.addLap': 'Thêm chặng',
    'log.needDistance': 'Nhập quãng đường để tính điểm',
    'log.needDuration': 'Nhập thời lượng để tính điểm',
    'log.titlePlaceholder': 'Tiêu đề (VD: {sport} sáng)',
    'log.guideLink': 'Hướng dẫn {sport} cho người mới',
    'points.earned': 'Buổi này được',
    'unit.pt': 'đ',
    'photo.add': 'Thêm ảnh (tuỳ chọn)',
    'photo.note': 'Ảnh sẽ hiển thị với toàn bộ đồng nghiệp.',
    'visibility.title': 'Hiển thị',
    'visibility.company': 'Đồng nghiệp',
    'visibility.private': 'Chỉ mình tôi',
    'when.title': 'Khi nào',
    'save.discard': 'Huỷ buổi tập',
    'save.discardConfirm': 'Huỷ buổi tập?',
    'common.notFound': 'Không tìm thấy "{q}"',

    // ── Chọn môn (PickActivity) ─────────────────
    'pick.title': 'BẠN VỪA TẬP GÌ?',
    'pick.subtitle': 'Ghi lại để giữ chuỗi và cộng điểm.',
    'pick.favorites': 'BẠN HAY TẬP',
    'pick.all': 'TẤT CẢ MÔN',

    // ── Onboarding ──────────────────────────────
    'ob.welcome': 'Chào mừng!',
    'ob.intro': 'Vài thông tin để bắt đầu. Bạn có thể đổi lại bất cứ lúc nào trong Cài đặt.',
    'ob.name': 'Tên hiển thị',
    'ob.namePlaceholder': 'Tên của bạn',
    'ob.dept': 'Phòng ban / Trung tâm',
    'ob.deptPlaceholder': 'Chọn hoặc gõ để tìm…',
    'ob.sports': 'Môn bạn hay tập (tuỳ chọn)',
    'ob.privacyTitle': 'Riêng tư:',
    'ob.privacyBody': 'Cân nặng và số đo của bạn luôn riêng tư, không ai thấy. Buổi tập của bạn hiển thị với đồng nghiệp trong bảng tin — bạn có thể đặt riêng tư từng buổi bất cứ lúc nào.',
    'ob.start': 'Bắt đầu',
    'ob.saving': 'Đang lưu…',

    // ── Màn mừng sau buổi tập ───────────────────
    'celeb.title': 'Xong buổi {sport}!',
    'celeb.streakUp': 'Chuỗi của bạn lên {n} ngày.',
    'celeb.streakRecord': 'Chuỗi của bạn lên {n} ngày — kỷ lục mới!',
    'celeb.streakFirst': 'Buổi đầu tiên — chuỗi bắt đầu từ hôm nay.',
    'celeb.newBadges': 'Huy hiệu mới',
    'celeb.newPR': 'PR mới',
    'celeb.toFeed': 'Về bảng tin',

    // ── Trang chủ ───────────────────────────────
    'home.streak': 'CHUỖI LIÊN TIẾP',
    'home.days': 'NGÀY',
    'home.atRisk': 'Tập hôm nay để giữ chuỗi {n} ngày nhé!',
    'home.weekSessions': 'Buổi tuần',
    'home.minutes': 'Phút',
    'home.weeklyGoal': 'MỤC TIÊU TUẦN',
    'home.ofSessions': '/{n} buổi',
    'home.goalDone': 'Vượt mục tiêu tuần này rồi. Đặt mốc cao hơn?',
    'home.goalLeft': 'Còn {n} buổi nữa là đạt mục tiêu tuần.',
    'home.recent': 'GẦN ĐÂY',
    'home.seeAll': 'Tất cả ›',

    // ── Ngôn ngữ (Settings + SignIn) ────────────
    'lang.title': 'Ngôn ngữ',
    'lang.vi': 'Tiếng Việt',
    'lang.en': 'English',

    // ── Mức gắng sức (RPE) ──────────────────────
    'rpe.field.label': 'Buổi tập nặng cỡ nào?',
    'rpe.field.hint': 'Chọn theo cảm giác trong lúc tập, không phải sau khi xong.',
    'rpe.1.label': 'Rất nhẹ',
    'rpe.1.desc': 'Như đi dạo. Thở đều, hát được cả bài, tập cả tiếng cũng không mệt.',
    'rpe.2.label': 'Nhẹ',
    'rpe.2.desc': 'Ấm người, ra mồ hôi nhẹ. Vẫn trò chuyện thoải mái từng câu.',
    'rpe.3.label': 'Vừa',
    'rpe.3.desc': 'Thở gấp hơn, nói được câu dài nhưng hát thì hụt hơi. Đang gắng nhưng vẫn kiểm soát.',
    'rpe.4.label': 'Nặng',
    'rpe.4.desc': 'Thở dốc, mỗi lần chỉ nói được vài từ. Cơ mỏi, bắt đầu muốn nghỉ.',
    'rpe.5.label': 'Gắng sức tối đa',
    'rpe.5.desc': 'Hết sức. Gần như không nói nổi, tim đập mạnh, chỉ trụ thêm được chút.',

    // ── Ghi buổi tập / nhật ký ──────────────────
    'save.note.title': 'Nhật ký buổi tập',
    'save.note.placeholder': 'VD: Chạy xong đầu óc nhẹ hẳn — đúng thứ mình cần hôm nay.',
    'edit.titleLabel': 'Tiêu đề',

    // ── Tên môn (hiển thị) ──────────────────────
    'sport.gym.label': 'Tập gym', 'sport.gym.verb': 'đã hoàn thành buổi',
    'sport.run.label': 'Chạy bộ', 'sport.run.verb': 'đã chạy',
    'sport.walk.label': 'Đi bộ', 'sport.walk.verb': 'đã đi bộ',
    'sport.cycle.label': 'Đạp xe', 'sport.cycle.verb': 'đã đạp xe',
    'sport.swim.label': 'Bơi', 'sport.swim.verb': 'đã bơi',
    'sport.hiking.label': 'Leo núi', 'sport.hiking.verb': 'đã leo núi',
    'sport.yoga.label': 'Yoga', 'sport.yoga.verb': 'đã tập yoga',
    'sport.football.label': 'Bóng đá', 'sport.football.verb': 'đã chơi bóng đá',
    'sport.basketball.label': 'Bóng rổ', 'sport.basketball.verb': 'đã chơi bóng rổ',
    'sport.badminton.label': 'Cầu lông', 'sport.badminton.verb': 'đã chơi cầu lông',
    'sport.tennis.label': 'Tennis', 'sport.tennis.verb': 'đã chơi tennis',
    'sport.pickleball.label': 'Pickleball', 'sport.pickleball.verb': 'đã chơi pickleball',
    'sport.other.label': 'Khác', 'sport.other.verb': 'đã tập',

    // ── Nhãn ô nhập ─────────────────────────────
    'field.durationMin': 'Thời lượng (phút)',
    'field.distanceKm': 'Quãng đường (km)',
    'field.distanceM': 'Quãng đường (m)',
    'field._pace': 'Pace',
    'field._pace100': 'Pace /100m',
    'field._speed': 'Tốc độ TB',
    'field.elevM': 'Độ cao (m)',
    'field.elevGainM': 'Độ cao leo (m)',
    'field.hrAvg': 'Nhịp tim TB (bpm)',
    'field.stepK': 'Số bước (nghìn)',
    'field.place': 'Địa điểm',
    'field.poolLen': 'Chiều dài bể',
    'field.goal': 'Mục tiêu',
    'field.periods': 'Số hiệp',
    'field.games': 'Số ván',

    // ── Đơn vị ──────────────────────────────────
    'unit.min': 'phút',
    'unit.points': 'điểm',
    'stat.duration': 'Thời lượng',
    'stat.effort': 'Gắng sức',
    'stat.points': 'Điểm',
    'stat.distance': 'Quãng đường',
    'stat.pace': 'Pace',
    'stat.avgSpeed': 'Tốc độ TB',
    'stat.volume': 'Tổng volume',
    'stat.sets': 'Tổng set',
    'stat.time': 'Thời gian',
    'stat.exCount': 'Số bài tập',
    'stat.generic': 'Chỉ số',
    'unit.ex': 'bài',

    // ── Chương trình gym (ProgsTab / CreateProg / PickEx) ───────
    'progs.title': 'Chương trình',
    'progs.new': 'Tạo mới',
    'progs.emptyMsg': 'Chưa có chương trình',
    'progs.emptySub': 'Nhấn "+ Tạo mới" để bắt đầu',
    'progs.delConfirm': 'Xoá "{name}"?',
    'cp.needName': 'Nhập tên chương trình!',
    'cp.needDayNames': 'Nhập tên cho tất cả các ngày!',
    'cp.needEx': 'Mỗi ngày cần ít nhất 1 bài tập!',
    'cp.editTitle': 'Sửa chương trình',
    'cp.newTitle': 'Tạo chương trình',
    'cp.progNamePlaceholder': 'Tên chương trình (VD: Push Pull Legs)',
    'cp.dayNamePlaceholder': 'Tên ngày (Push, Chân, Full Body...)',
    'cp.searchEx': 'Tìm bài tập…',
    'cp.addDay': 'Thêm ngày',
    'pe.title': 'Chọn bài tập',
    'pe.all': 'Tất cả',
    'pe.emptyMsg': 'Không tìm thấy bài tập',
    'pe.emptySub': 'Thử nhóm cơ khác hoặc từ khoá khác',
    'pe.newEx': 'Tạo bài tập mới',
    'pe.newExTitle': 'Bài tập mới',
    'pe.exNamePlaceholder': 'Tên bài tập…',

    // ── Đang tập (ActiveWorkout) + Lưu buổi gym ─────────────────
    'aw.training': 'Đang tập: {name}',
    'aw.resume': 'Tiếp tục',
    'aw.restTime': 'Thời gian nghỉ',
    'aw.restDone': 'Hết giờ! Tiếp tục tập thôi 🔥',
    'aw.restIn': 'Tiếp tục sau {t}',
    'aw.lastTime': 'Lần trước: {v}',
    'aw.exNote': 'Ghi chú bài tập…',
    'aw.addEx': 'Thêm bài tập',
    'sw.title': 'Lưu buổi tập',
    'sw.namePlaceholder': 'Tên buổi tập',
    'common.guide': 'Hướng dẫn',
    'common.saving': 'Đang lưu…',
    'common.add': 'Thêm',
    'common.dismiss': 'Bỏ qua',
    'common.exit': 'Thoát',
    'photo.short': 'Thêm ảnh',

    // ── Chi tiết buổi tập (sửa/xoá) ─────────────────────────────
    'sd.delConfirm': 'Xoá bài đăng này? Số liệu (điểm, phút, buổi, chuỗi, xếp hạng) sẽ được trừ lại. Không hoàn tác được.',
    'sd.photoRemoved': 'Đã gỡ ảnh — bấm để thêm ảnh mới',
    'sd.visNote': 'Chuyển sang "Chỉ mình tôi" sẽ gỡ buổi này khỏi bảng tin & bảng xếp hạng của đồng nghiệp.',
    'sd.editNote': 'Sửa tiêu đề, ghi chú & ảnh. Điểm, chuỗi và xếp hạng giữ nguyên như lúc đăng.',
    'sd.saveConfirm': 'Lưu thay đổi cho bài này?',
    'sd.laps': 'Chi tiết chặng',

    // ── Tiến độ cá nhân (ProgressTab) ───────────────────────────
    'pt.emptyMsg': 'Chưa có dữ liệu',
    'pt.emptySub': 'Hoàn thành buổi tập để thấy tiến bộ ở đây',
    'pt.weight': 'Cân nặng (riêng tư 🔒)',
    'pt.latest': 'Gần nhất',
    'pt.noData': 'Chưa có dữ liệu',
    'pt.weeklyGoal': 'Mục tiêu tuần này',
    'pt.goalPrompt': 'Đặt mục tiêu để giữ thói quen đều đặn.',
    'pt.setGoal': 'Đặt mục tiêu',
    'pt.sessPerWeek': 'Số buổi / tuần',
    'pt.minPerWeek': 'Số phút / tuần',
    'pt.goalHint': 'Để 0 nếu không đặt mục tiêu đó. Gợi ý WHO: 150 phút/tuần.',
    'pt.sessions': 'Buổi tập',
    'pt.activeMin': 'Phút vận động',
    'pt.editGoal': 'Sửa mục tiêu',
    'pt.pr': 'Kỷ lục cá nhân',
    'pt.weekPoints': 'Điểm tuần',
    'pt.weekMin': 'Phút tuần',
    'pt.weekSess': 'Buổi tuần',
    'pt.breakdown': 'Phân bổ theo môn',
    'pt.days90': '90 ngày',
    'pt.countMin': '{c} buổi · {m} phút',
    'pt.pointsByWeek': 'Điểm theo tuần',
    'pt.bestSpeed': 'Tốc độ tốt nhất',
    'pt.bestPace': 'Pace tốt nhất',
    'pt.longest': 'Dài nhất',
    'pt.sessCount': 'Số buổi',
    'pt.distByWeek': 'Quãng đường theo tuần ({u})',
    'pt.needMore': 'Cần thêm buổi để thấy xu hướng',
    'pt.totalMin': 'Tổng phút',
    'pt.totalPts': 'Tổng điểm',
    'pt.overview': 'Tổng quan',
    'pt.byExercise': 'Theo bài tập',
    'pt.bySession': 'Theo buổi tập',
    'pt.noExData': 'Chưa có dữ liệu bài tập',
    'pt.thisWeek': 'Tuần này',
    'pt.lastWeek': 'Tuần trước',
    'pt.prHeaviest': 'PR Tạ nặng nhất',
    'pt.noSessData': 'Chưa có dữ liệu buổi tập',
    'pt.mostRecent': 'Lần gần nhất',
    'pt.previous': 'Lần trước đó',
    'pt.history': 'Lịch sử các lần tập',
    'pt.weightPrompt': 'Cân nặng hôm nay (kg):',

    // ── Cấp app: lời mời, banner quản trị, lỗi ──────────────────
    'invite.title': 'Bạn có lời mời vào nhóm',
    'invite.from': '{name} mời bạn',
    'invite.generic': 'Bạn được mời',
    'admin.banner': '🛡 Chế độ quản trị đang bật — bạn có thể xoá bài & bình luận của mọi người.',
    'chat.aria': 'Trợ lý AI',
    'err.loadProfile': 'Không tải được hồ sơ',
    'err.saveGoals': 'Lưu mục tiêu thất bại',
    'err.deleteAccount': 'Không xoá được tài khoản',
    'err.uploadPhoto': 'Upload ảnh thất bại',
    'err.editSession': 'Sửa buổi tập thất bại',
    'err.changeVis': 'Đổi hiển thị thất bại',
    'err.deletePost': 'Xoá bài thất bại',
    'err.adminDelete': 'Xoá bài (quản trị) thất bại',
    'err.joinClub': 'Vào nhóm thất bại',
    'err.syncSession': 'Đồng bộ buổi tập thất bại',
  },

  en: {
    // ── Common ──────────────────────────────────
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.loading': 'Loading…',
    'common.required': 'Required',

    // ── Log session form (LogActivity + SaveWorkout) ────────────
    'log.more': 'More details',
    'log.less': 'Show less',
    'log.laps': 'Splits / laps (optional)',
    'log.addLap': 'Add split',
    'log.needDistance': 'Enter distance to score',
    'log.needDuration': 'Enter duration to score',
    'log.titlePlaceholder': 'Title (e.g. Morning {sport})',
    'log.guideLink': '{sport} guide for beginners',
    'points.earned': 'This session',
    'unit.pt': 'pt',
    'photo.add': 'Add photo (optional)',
    'photo.note': 'Your photo is visible to all colleagues.',
    'visibility.title': 'Visibility',
    'visibility.company': 'Colleagues',
    'visibility.private': 'Only me',
    'when.title': 'When',
    'save.discard': 'Discard session',
    'save.discardConfirm': 'Discard this session?',
    'common.notFound': 'No match for "{q}"',

    // ── Pick activity ───────────────────────────
    'pick.title': 'WHAT DID YOU DO?',
    'pick.subtitle': 'Log it to keep your streak and earn points.',
    'pick.favorites': 'YOUR GO-TOS',
    'pick.all': 'ALL SPORTS',

    // ── Onboarding ──────────────────────────────
    'ob.welcome': 'Welcome!',
    'ob.intro': 'A few details to get started. You can change them anytime in Settings.',
    'ob.name': 'Display name',
    'ob.namePlaceholder': 'Your name',
    'ob.dept': 'Department / Center',
    'ob.deptPlaceholder': 'Pick or type to search…',
    'ob.sports': 'Sports you usually do (optional)',
    'ob.privacyTitle': 'Privacy:',
    'ob.privacyBody': 'Your weight and measurements are always private — no one can see them. Your sessions appear to colleagues in the feed, and you can make any session private anytime.',
    'ob.start': 'Get started',
    'ob.saving': 'Saving…',

    // ── Post-session celebration ────────────────
    'celeb.title': '{sport} done!',
    'celeb.streakUp': 'Your streak is now {n} days.',
    'celeb.streakRecord': 'Your streak is now {n} days — new record!',
    'celeb.streakFirst': 'First session — your streak starts today.',
    'celeb.newBadges': 'New badge',
    'celeb.newPR': 'New PR',
    'celeb.toFeed': 'Back to feed',

    // ── Home ────────────────────────────────────
    'home.streak': 'CURRENT STREAK',
    'home.days': 'DAYS',
    'home.atRisk': 'Train today to keep your {n}-day streak!',
    'home.weekSessions': 'Sessions',
    'home.minutes': 'Minutes',
    'home.weeklyGoal': 'WEEKLY GOAL',
    'home.ofSessions': '/{n} sessions',
    'home.goalDone': "You've beaten this week's goal. Aim higher?",
    'home.goalLeft': '{n} more to hit your weekly goal.',
    'home.recent': 'RECENT',
    'home.seeAll': 'See all ›',

    // ── Language ────────────────────────────────
    'lang.title': 'Language',
    'lang.vi': 'Tiếng Việt',
    'lang.en': 'English',

    // ── Effort (RPE) ────────────────────────────
    'rpe.field.label': 'How hard was it?',
    'rpe.field.hint': 'Pick how it felt during the session, not after.',
    'rpe.1.label': 'Very light',
    'rpe.1.desc': 'Like a stroll. Easy breathing, could sing, could go for an hour.',
    'rpe.2.label': 'Light',
    'rpe.2.desc': 'Warmed up, light sweat. Still chatting in full sentences.',
    'rpe.3.label': 'Moderate',
    'rpe.3.desc': 'Breathing harder, can talk but not sing. Working, still in control.',
    'rpe.4.label': 'Hard',
    'rpe.4.desc': 'Breathing heavy, only a few words at a time. Muscles tiring.',
    'rpe.5.label': 'Max effort',
    'rpe.5.desc': 'All out. Can\'t talk, heart pounding, little left in the tank.',

    // ── Log session / journal ───────────────────
    'save.note.title': 'Session journal',
    'save.note.placeholder': 'e.g. Cleared my head after that run — just what I needed today.',
    'edit.titleLabel': 'Title',

    // ── Sport names (display) ───────────────────
    'sport.gym.label': 'Gym', 'sport.gym.verb': 'finished',
    'sport.run.label': 'Running', 'sport.run.verb': 'ran',
    'sport.walk.label': 'Walking', 'sport.walk.verb': 'walked',
    'sport.cycle.label': 'Cycling', 'sport.cycle.verb': 'cycled',
    'sport.swim.label': 'Swimming', 'sport.swim.verb': 'swam',
    'sport.hiking.label': 'Hiking', 'sport.hiking.verb': 'hiked',
    'sport.yoga.label': 'Yoga', 'sport.yoga.verb': 'did yoga —',
    'sport.football.label': 'Football', 'sport.football.verb': 'played football —',
    'sport.basketball.label': 'Basketball', 'sport.basketball.verb': 'played basketball —',
    'sport.badminton.label': 'Badminton', 'sport.badminton.verb': 'played badminton —',
    'sport.tennis.label': 'Tennis', 'sport.tennis.verb': 'played tennis —',
    'sport.pickleball.label': 'Pickleball', 'sport.pickleball.verb': 'played pickleball —',
    'sport.other.label': 'Other', 'sport.other.verb': 'worked out —',

    // ── Input field labels ──────────────────────
    'field.durationMin': 'Duration (min)',
    'field.distanceKm': 'Distance (km)',
    'field.distanceM': 'Distance (m)',
    'field._pace': 'Pace',
    'field._pace100': 'Pace /100m',
    'field._speed': 'Avg speed',
    'field.elevM': 'Elevation (m)',
    'field.elevGainM': 'Elevation gain (m)',
    'field.hrAvg': 'Avg heart rate (bpm)',
    'field.stepK': 'Steps (thousands)',
    'field.place': 'Location',
    'field.poolLen': 'Pool length',
    'field.goal': 'Focus',
    'field.periods': 'Periods',
    'field.games': 'Games',

    // ── Units ───────────────────────────────────
    'unit.min': 'min',
    'unit.points': 'pts',
    'stat.duration': 'Duration',
    'stat.effort': 'Effort',
    'stat.points': 'Points',
    'stat.distance': 'Distance',
    'stat.pace': 'Pace',
    'stat.avgSpeed': 'Avg speed',
    'stat.volume': 'Total volume',
    'stat.sets': 'Total sets',
    'stat.time': 'Time',
    'stat.exCount': 'Exercises',
    'stat.generic': 'Stat',
    'unit.ex': '',

    // ── Gym programs (ProgsTab / CreateProg / PickEx) ───────────
    'progs.title': 'Programs',
    'progs.new': 'New',
    'progs.emptyMsg': 'No programs yet',
    'progs.emptySub': 'Tap "+ New" to start',
    'progs.delConfirm': 'Delete "{name}"?',
    'cp.needName': 'Enter a program name!',
    'cp.needDayNames': 'Name all days!',
    'cp.needEx': 'Each day needs at least 1 exercise!',
    'cp.editTitle': 'Edit program',
    'cp.newTitle': 'New program',
    'cp.progNamePlaceholder': 'Program name (e.g. Push Pull Legs)',
    'cp.dayNamePlaceholder': 'Day name (Push, Legs, Full Body...)',
    'cp.searchEx': 'Search exercises…',
    'cp.addDay': 'Add day',
    'pe.title': 'Pick exercise',
    'pe.all': 'All',
    'pe.emptyMsg': 'No exercises found',
    'pe.emptySub': 'Try another muscle group or keyword',
    'pe.newEx': 'Create new exercise',
    'pe.newExTitle': 'New exercise',
    'pe.exNamePlaceholder': 'Exercise name…',

    // ── Active workout + save gym session ───────────────────────
    'aw.training': 'Training: {name}',
    'aw.resume': 'Resume',
    'aw.restTime': 'Rest time',
    'aw.restDone': "Time's up! Back to it 🔥",
    'aw.restIn': 'Resume in {t}',
    'aw.lastTime': 'Last time: {v}',
    'aw.exNote': 'Exercise note…',
    'aw.addEx': 'Add exercise',
    'sw.title': 'Save session',
    'sw.namePlaceholder': 'Session name',
    'common.guide': 'Guide',
    'common.saving': 'Saving…',
    'common.add': 'Add',
    'common.dismiss': 'Dismiss',
    'common.exit': 'Exit',
    'photo.short': 'Add photo',

    // ── Session detail (edit/delete) ────────────────────────────
    'sd.delConfirm': "Delete this post? Your stats (points, minutes, sessions, streak, ranking) will be deducted. This can't be undone.",
    'sd.photoRemoved': 'Photo removed — tap to add a new one',
    'sd.visNote': 'Switching to "Only me" removes this session from your colleagues\' feed and leaderboard.',
    'sd.editNote': 'Edit title, note & photo. Points, streak and ranking stay as posted.',
    'sd.saveConfirm': 'Save changes to this post?',
    'sd.laps': 'Split details',

    // ── Personal progress (ProgressTab) ─────────────────────────
    'pt.emptyMsg': 'No data yet',
    'pt.emptySub': 'Finish a session to see your progress here',
    'pt.weight': 'Weight (private 🔒)',
    'pt.latest': 'Latest',
    'pt.noData': 'No data yet',
    'pt.weeklyGoal': "This week's goal",
    'pt.goalPrompt': 'Set a goal to keep a steady habit.',
    'pt.setGoal': 'Set goal',
    'pt.sessPerWeek': 'Sessions / week',
    'pt.minPerWeek': 'Minutes / week',
    'pt.goalHint': 'Leave 0 to skip that goal. WHO suggests 150 min/week.',
    'pt.sessions': 'Sessions',
    'pt.activeMin': 'Active minutes',
    'pt.editGoal': 'Edit goal',
    'pt.pr': 'Personal records',
    'pt.weekPoints': 'Points this week',
    'pt.weekMin': 'Minutes this week',
    'pt.weekSess': 'Sessions this week',
    'pt.breakdown': 'By sport',
    'pt.days90': '90 days',
    'pt.countMin': '{c} sessions · {m} min',
    'pt.pointsByWeek': 'Points by week',
    'pt.bestSpeed': 'Best speed',
    'pt.bestPace': 'Best pace',
    'pt.longest': 'Longest',
    'pt.sessCount': 'Sessions',
    'pt.distByWeek': 'Distance by week ({u})',
    'pt.needMore': 'Need more sessions to see a trend',
    'pt.totalMin': 'Total minutes',
    'pt.totalPts': 'Total points',
    'pt.overview': 'Overview',
    'pt.byExercise': 'By exercise',
    'pt.bySession': 'By session',
    'pt.noExData': 'No exercise data yet',
    'pt.thisWeek': 'This week',
    'pt.lastWeek': 'Last week',
    'pt.prHeaviest': 'Heaviest lift PR',
    'pt.noSessData': 'No session data yet',
    'pt.mostRecent': 'Most recent',
    'pt.previous': 'Previous',
    'pt.history': 'Session history',
    'pt.weightPrompt': "Today's weight (kg):",

    // ── App level: invites, admin banner, errors ────────────────
    'invite.title': 'You have a club invite',
    'invite.from': '{name} invited you',
    'invite.generic': "You're invited",
    'admin.banner': "🛡 Moderation mode is on — you can delete anyone's posts & comments.",
    'chat.aria': 'AI assistant',
    'err.loadProfile': "Couldn't load profile",
    'err.saveGoals': 'Failed to save goal',
    'err.deleteAccount': "Couldn't delete account",
    'err.uploadPhoto': 'Photo upload failed',
    'err.editSession': 'Failed to edit session',
    'err.changeVis': 'Failed to change visibility',
    'err.deletePost': 'Failed to delete post',
    'err.adminDelete': 'Failed to delete post (admin)',
    'err.joinClub': 'Failed to join club',
    'err.syncSession': 'Failed to sync session',
  },
};
